---
project_name: git-credential-1password
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ldflags:
      - -s -w
      - -X github.com/develerik/git-credential-1password/cmd.Version={{.Version}}
      - -X github.com/develerik/git-credential-1password/cmd.Build={{.Commit}}
      - -X github.com/develerik/git-credential-1password/cmd.Date={{.Date}}
archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
release:
  prerelease: auto
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999
brews:
  - homepage: https://github.com/develerik/homebrew-tools
    tap:
      owner: develerik
      name: homebrew-tools
    description: "Helper to store git credentials inside 1password."
    license: "ISC"
    folder: Formula
    dependencies:
      - name: git
